---
- hosts: lasersaur
  become: yes

  roles:
    - common
    - lasersaur

  vars_files:
    - vars/lasersaur.vault.yml

  vars:
    - lasersaur_user: fabi
    - lasersaur_dir: /home/fabi/LasaurApp
    - lasersaur_config:
        cookie_key: "{{ lasersaur_cookie_key }}"
        tolerance: 0.01
        serial_port: '/dev/ttyACM0'
        open_browser: false
        public: true
        network_port: 80
        use_id_card_access_restriction: true
