---
- src: https://github.com/morbidick/ansible-role-common
  name: common

- src: https://github.com/morbidick/ansible-role-dnsmasq
  name: dnsmasq

- src: https://github.com/morbidick/ansible-role-youtube-dl
  name: youtube-dl

- src: https://github.com/bertvv/ansible-role-samba
  name: samba

- src: https://github.com/geerlingguy/ansible-role-nfs
  name: nfs

- src: https://github.com/morbidick/ansible-role-lasersaur
  name: lasersaur
